
name = "DashAggridJs"
uuid = "1b08a953-4be3-4667-9a23-42bdf1ba7241"
authors = ["Scott Kilgore <skilgore@landmarktx.com>"]
version = "0.4.11"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
